
export MYDIR=$(pwd -P)
export ROOTDIR=$(cd ../../.. && pwd -P)
export CTFBINDIR=${ROOTDIR}/projects/illumos/usr/src/tools/proto/*/opt/onbld/bin/i386
export CTFMERGE=${CTFBINDIR}/ctfmerge
export CTFCONVERT=${CTFBINDIR}/ctfconvert
export ALTCTFCONVERT=${CTFBINDIR}/ctfconvert-altexec

#export CURL_CFLAGS="-DDEBUG_KVM -DDEBUG_BLK_MIGRATION -DDEBUG_MIGRATION -DDEBUG_MIGRATION_EXEC -DDEBUG_MIGRATION_FD -DDEBUG_MIGRATION_TCP -DDEBUG_MIGRATION_UNIX -DDEBUG_IOAPIC -DDEBUG_OPENPIC -DDEBUG_PIC"
gmake -f Makefile.joyent qemu

echo
echo Output is in: ${MYDIR}/x86_64-softmmu/qemu-system-x86_64


#-DDEBUG_KVM
#-DDEBUG_BLK_MIGRATION
#-DDEBUG_MIGRATION
#-DDEBUG_MIGRATION_EXEC
#-DDEBUG_MIGRATION_FD
#-DDEBUG_MIGRATION_TCP
#-DDEBUG_MIGRATION_UNIX
#-DDEBUG_IOAPIC
#-DDEBUG_OPENPIC
#-DDEBUG_PIC
#
#-DDEBUG
#-DDEBUG_AHCI
#-DDEBUG_ASI
#-DDEBUG_BITBANG_I2C
#-DDEBUG_BONITO
#-DDEBUG_BUFFERED_FILE
#-DDEBUG_CACHE_CONTROL
#-DDEBUG_COALESCED
#-DDEBUG_COMMPAGE
#-DDEBUG_CURL
#-DDEBUG_EMPTY_SLOT
#-DDEBUG_ESP
#-DDEBUG_FEC
#-DDEBUG_G364
#-DDEBUG_GIC
#-DDEBUG_IRQ
#-DDEBUG_KBD
#-DDEBUG_LAN9118
#-DDEBUG_LED
#-DDEBUG_LSI
#-DDEBUG_MACHLOAD
#-DDEBUG_MEMREG
#-DDEBUG_MMU
#-DDEBUG_MSD
#-DDEBUG_MXCC
#-DDEBUG_OHCI
#-DDEBUG_PL022
#-DDEBUG_PL031
#-DDEBUG_PL061
#-DDEBUG_PL181
#-DDEBUG_PSTATE
#-DDEBUG_RC4030
#-DDEBUG_SCSI
#-DDEBUG_SD
#-DDEBUG_SERIAL
#-DDEBUG_SMBUS
#-DDEBUG_SONIC
#-DDEBUG_SSD0303
#-DDEBUG_SSD0323
#-DDEBUG_SSI_SD
#-DDEBUG_STELLARIS_ENET
#-DDEBUG_SYBORG_FB
#-DDEBUG_SYBORG_INT
#-DDEBUG_SYBORG_KEYBOARD
#-DDEBUG_SYBORG_SERIAL
#-DDEBUG_SYBORG_TIMER
#-DDEBUG_SYBORG_VIRTIO
#-DDEBUG_Serial
#-DDEBUG_VMMOUSE
#-DDEBUG_VT82C686B
#-DHPET_DEBUG
#-DPFLASH_DEBUG
#-DVNIC_DHCP_DEBUG
