# Automatically generated by configure - do not modify
SRC_PATH=/home/builder/devel/smartos-live/projects/local/kvm-cmd/roms/vgabios
CC=/home/builder/devel/smartos-live/proto/usr/bin/gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
LD=gld
